FROM node:22-alpine AS react-build

WORKDIR /app

EXPOSE 3000

COPY package.json /app

COPY package-lock.json /app

RUN npm install

COPY . /app

ENV NODE_OPTIONS="--max-old-space-size=4096"

CMD [ "npm", "run", "start"]



