services:
  prank-mongo:
    image: mongo:8.0
    container_name: prank_mongo_container
    networks:
      - prank-app-net
    restart: always
    volumes:
      - mongo_database:/data/db
  prank-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: prank_server_container
    networks:
      - traefik-net
      - prank-app-net
    ports:
      - '${SERVER_OUTSIDE_PORT}:${SERVER_DOCKER_PORT}'
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./server/src:/app/src
      - uploads_data:/app/src/uploads
    restart: always
    depends_on:
      - prank-mongo
    labels:
      - 'traefik.enable=true'
      # --- РОУТЕР ДЛЯ API ---
      - "traefik.http.routers.prank-api.rule=Host(`prank-sound.ru`) && PathPrefix(`/api`)"
      - "traefik.http.routers.prank-api.entrypoints=websecure"
      - "traefik.http.routers.prank-api.tls.certresolver=myresolver"
      - "traefik.http.routers.prank-api.priority=100"
      - "traefik.http.routers.prank-api.service=prank-backend" # Явно указываем сервис

      # --- РОУТЕР ДЛЯ СТАТИКИ ---
      - "traefik.http.routers.prank-static.rule=Host(`prank-sound.ru`) && PathPrefix(`/static`)"
      - "traefik.http.routers.prank-static.entrypoints=websecure"
      - "traefik.http.routers.prank-static.tls.certresolver=myresolver"
      - "traefik.http.routers.prank-static.priority=100"
      - "traefik.http.routers.prank-static.service=prank-backend" # Тот же сервис

      # --- ОБЩИЙ СЕРВИС (Node.js порт) ---
      - "traefik.http.services.prank-backend.loadbalancer.server.port=5000"
  prank-client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: prank_client_container
    networks:
      - traefik-net
      - prank-app-net
    ports:
      - '${CLIENT_OUTSIDE_PORT}:${CLIENT_DOCKER_PORT}'
    volumes:
      - ./client/src:/app/src
    restart: always
    depends_on:
      - prank-server
    labels:
      - 'traefik.enable=true'
      # Основной домен сайта
      - 'traefik.http.routers.prank-front.rule=Host(`prank-sound.ru`)'
      - 'traefik.http.routers.prank-front.entrypoints=websecure'
      - 'traefik.http.routers.prank-front.tls.certresolver=myresolver'
      # Порт, на котором работает React/Nginx внутри контейнера. Для dev указываем порт Vite, prod - порт Nginx
      - 'traefik.http.services.prank-front.loadbalancer.server.port=3000'
      # ПРИОРИТЕТ 10 (самый низкий)
      # Это правило "по умолчанию" для всего, что не попало в /api
      - 'traefik.http.routers.prank-front.priority=10'

  prank-mongo-express:
    image: mongo-express:1.0
    container_name: prank_mongo_express_container
    networks:
      - traefik-net
      - prank-app-net
    ports:
      - '${ME_OUTSIDE_PORT}:${ME_DOCKER_PORT}'
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    restart: always
    labels:
      - 'traefik.enable=true'
      # 1. Правило: Тот же основной домен + путь /db-admin
      - 'traefik.http.routers.prank-me.rule=Host(`prank-sound.ru`) && PathPrefix(`/db-admin`)'
      - 'traefik.http.routers.prank-me.entrypoints=websecure'
      - 'traefik.http.routers.prank-me.tls.certresolver=myresolver'

      # 2. ПРИОРИТЕТ: Ставим выше, чем у фронтенда (10) и бэкенда (100)
      - 'traefik.http.routers.prank-me.priority=110'

      # 3. MIDDLEWARE: Отрезаем приставку /db-admin перед отправкой в контейнер
      # Чтобы запрос 'sportplans.ru/db-admin/assets/app.js' стал '/assets/app.js'
      - 'traefik.http.middlewares.prank-me-strip.stripprefix.prefixes=/db-admin'
      - 'traefik.http.routers.prank-me.middlewares=prank-me-strip'

      # 4. ПОРТ: Внутренний порт mongo-express
      - 'traefik.http.services.prank-me.loadbalancer.server.port=8081'

volumes:
  mongo_database:
  uploads_data:

networks:
  # Внешняя сеть для связи с Traefik
  traefik-net:
    external: true
    driver_opts:
      com.docker.network.driver.mtu: "1500" # Чтобы Docker всегда помнил про MTU
  # Внутренняя сеть для связи Backend <-> MongoDB
  prank-app-net:
    driver: bridge
